"""initial schema

Revision ID: 175ac57a3ebf
Revises: 
Create Date: 2026-09-23 14:36:58.706906

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '175ac57a3ebf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
