"""migration message

Revision ID: 5edfd7135860
Revises: 175ac57a3ebf
Create Date: 2026-09-23 15:04:55.704932

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5edfd7135860'
down_revision: str | Sequence[str] | None = '175ac57a3ebf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
